[tox]
; requires =
    ; tox-conda
    ; setuptools
envlist =
	py{39,310,311,312,313,314}-{oldest,latest}
    build_docs

isolated_build = true

[testenv]
description = run the tests with pytest
passenv = CI, GITHUB_*
deps =
    pytest
    
    numpy
    xarray
    matplotlib
    pandas
    fair
    netCDF4

    oldest: numpy==1.21.*
    oldest: xarray==0.20.*
    oldest: matplotlib==3.5.*
    oldest: pandas==1.3.*

    latest: numpy
    latest: xarray
    latest: matplotlib
    latest: pandas

# skip_install = true

# Pass through the following environment variables which may be needed for the CI
# passenv = HOME WINDIR LC_ALL LC_CTYPE CC CI TRAVIS

# Run the tests in a temporary directory to make sure that we don't import
# this package from the source tree
# changedir = .tmp/{envname}

commands =
    pytest

[testenv:build_docs]
changedir = docs
description = invoke sphinx-build to build the HTML docs
extras = docs
commands =
    pip install -r requirements.txt
    sphinx-build -W -b html . _build/html
