name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Define the specific slices you want to test
        include:
          - python: '3.9'
            toxenv: py39-oldest

          - python: '3.9'
            toxenv: py39-latest

          - python: '3.14'
            toxenv: py314-latest

          - python: '3.14'
            toxenv: build_docs

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{matrix.python}}
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python}}

    - name: Install dependencies
      run: pip install tox

    - name: Test with tox
      run: tox -e ${{matrix.toxenv}}
